{% set name = "octokitpy" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c16d7053f44a1909025b656e10431e319d6567af1ee4b65636745581559a75c3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - octokitpy-routes >=2.2.0
    - python-jose >=3.1.0
    - requests >=2.23.0

test:
  imports:
    - octokit

about:
  home: https://github.com/khornberg/octokit.py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client for GitHub API
  doc_url: https://octokitpy.readthedocs.io/en/latest/
  dev_url: https://github.com/khornberg/octokit.py

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
