{% set name = "octokitpy" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0879c0e54dbd31aa304184d662ff09f543dafcd74e66fdf493063c77445ce57e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - octokitpy-routes >=2.2.0
    - python-jose >=3.1.0
    - requests >=2.23.0

test:
  imports:
    - octokit

about:
  home: https://github.com/khornberg/octokit.py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client for GitHub API
  doc_url: https://octokitpy.readthedocs.io/en/latest/
  dev_url: https://github.com/khornberg/octokit.py

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
